
# nmake makefile that creates JLOAD.EXE
# tools used:
#               default      alternate
#----------------------------------------------
# Assembler:    jwasm        MS masm (+Bin2Inc)
# OMF linker:   jwlink       MS link16
# COFF linker:  jwlink       -

# the 32-bit part of jload must be linked with base 0xF8400000;
# this isn't possible with (all?) MS link versions!

# bin2inc translates binary files to assembly include files.
# It's source is supplied with JWasm.

!ifndef DEBUG
DEBUG = 0
!endif

!if $(DEBUG)
OUTDIR = DEBUG
#AOPTD=-D_DEBUG -D?PEDBG=1 -D?RMDBG=1 -D?INITDBG=1 -D?JLMDBG=1
AOPTD=-Sg -D_DEBUG -D?INITDBG=1
!else
OUTDIR = RELEASE
AOPTD=
!endif

AOPT=-c -nologo $(AOPTD) -I..\..\Include -DOUTD=$(OUTDIR)

NAME  = JLOAD
NAME32= JLOAD32
VXD1  = VMM
VXD4  = VDMAD

!ifndef MASM
MASM=0
!endif

!if $(MASM)
ASM = ml.exe
NAMEBIN32=$(OUTDIR)\$(NAME32).inc
!else
ASM = jwasm.exe
NAMEBIN32=$(OUTDIR)\$(NAME32).bin
!endif

INC32=jload.inc jload32.inc debug.inc ..\..\Include\jsystem.inc ..\..\Include\jlm.inc
INC16=jload.inc             debug.inc ..\..\Include\jsystem.inc ..\..\Include\jlm.inc

ALL: $(OUTDIR) $(OUTDIR)\$(NAME).EXE

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)\$(NAME).EXE: $(OUTDIR)\$(NAME).obj MAKEFILE
#	@link16.exe /MAP:FULL/NOE/NON/ONERROR:NOEXE $*.OBJ, $*.EXE, $*.MAP;
	@jwlink.exe format dos file $*.obj name $*.EXE op q,m=$*

$(OUTDIR)\$(NAME).obj: $(NAME).asm $(NAMEBIN32) $(INC16)
	@$(ASM) $(AOPT) -Fl$(OUTDIR)\ -Fo=$* $(NAME).asm

$(NAMEBIN32): $(OUTDIR)\$(NAME32).obj $(OUTDIR)\$(VXD1).obj $(OUTDIR)\$(VXD4).obj
	@jwlink.exe format raw bin f { $*.obj $(OUTDIR)\$(VXD1).obj $(OUTDIR)\$(VXD4).obj } name $*.bin disable 1014 op q,map=$*,offset=0xF8400000,start=_start
!if $(MASM)
	@bin2inc.exe -q $*.bin $*.inc
!endif

$(OUTDIR)\$(NAME32).obj: $(NAME32).asm $(INC32) MAKEFILE
	@$(ASM) -coff $(AOPT) -Fl$(OUTDIR)\ -Fo=$* $(NAME32).asm

$(OUTDIR)\$(VXD1).obj: $(VXD1).asm $(INC32) MAKEFILE
	@$(ASM) -coff $(AOPT) -Fl$(OUTDIR)\ -Fo=$* $(VXD1).asm

$(OUTDIR)\$(VXD4).obj: $(VXD4).asm $(INC32) MAKEFILE
	@$(ASM) -coff $(AOPT) -Fl$(OUTDIR)\ -Fo=$* $(VXD4).asm

clean:
	@del $(OUTDIR)\*.EXE
	@if exist $(OUTDIR)\*.inc del $(OUTDIR)\*.inc
	@del $(OUTDIR)\*.bin
	@del $(OUTDIR)\*.obj
	@del $(OUTDIR)\*.lst
	@del $(OUTDIR)\*.map
