
# NMake/WMake Makefile to create IOTRAP.DLL
#
#  tools                      alternatives
#----------------------------------------------------------
#  JWasm                      Masm v6.x
#  JWLink                     MS Link, WLink, ALink
#  (PatchPE) 
# 
# PatchPE: HX tool to patch a PE binary to PX ( not required for jwlink ).

NAME = IOTRAP
OUTDIR=Release
AOPT=-c -coff -nologo -Fl$*.lst -Fo$*.obj -I..\..\Include
ASM=jwasm.exe
#LINK=link.exe /NOLOGO /SUBSYSTEM:CONSOLE /DLL $*.obj /OUT:$*.DLL /MAP:$*.MAP /EXPORT:ddb /Entry:DllMain /OPT:NOWIN98
LINK=jwlink format win nt hx file $*.obj name $*.DLL op q,MAP=$*.MAP export _ddb.1

ALL: $(OUTDIR) $(OUTDIR)\$(NAME).DLL $(OUTDIR)\TESTIOT.COM

$(OUTDIR):
	@mkdir $(OUTDIR)

$(OUTDIR)\$(NAME).DLL: $(OUTDIR)\$(NAME).obj Makefile
	@$(LINK)
#	@..\patchpe $*.DLL

$(OUTDIR)\$(NAME).obj: $(NAME).asm
	@$(ASM) $(AOPT) $(NAME).asm

$(OUTDIR)\TESTIOT.COM: TESTIOT.asm
	@$(ASM) -nologo -bin -Fo=$*.COM TESTIOT.asm
